  mysqltests:
    build:
      context: docker/blocks/mysql_tests
      args:
        - mysql_version=${mysql_version}
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: grafarg_tests
      MYSQL_USER: grafarg
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    tmpfs: /var/lib/mysql:rw
