+++
# -------------------------------------------------------------------------
# Do not edit this file. It is automatically generated by json-schema-docs.
# -------------------------------------------------------------------------
title = "plugin.json"
keywords = ["grafarg", "plugins", "documentation"]
aliases = ["/docs/grafarg/latest/plugins/developing/plugin.json/"]
+++

{{ .Markdown 1 }}
