#! /usr/bin/env bash

# Wrapper for the grafarg-cli binary
# This file serves as a wrapper for the grafarg-cli binary. It ensures we set
# the system-wide Grafarg configuration that was bundled with the package as we
# use the binary.

DEFAULT=/etc/default/grafarg

GRAFARG_HOME=/usr/share/grafarg
CONF_DIR=/etc/grafarg
DATA_DIR=/var/lib/grafarg
PLUGINS_DIR=/var/lib/grafarg/plugins
LOG_DIR=/var/log/grafarg

CONF_FILE=$CONF_DIR/grafarg.ini
PROVISIONING_CFG_DIR=$CONF_DIR/provisioning

EXECUTABLE=$GRAFARG_HOME/bin/grafarg-cli

if [ ! -x $EXECUTABLE ]; then
 echo "Program not installed or not executable"
 exit 5
fi

# overwrite settings from default file
if [ -f "$DEFAULT" ]; then
  . "$DEFAULT"
fi

OPTS="--homepath=${GRAFARG_HOME} \
      --config=${CONF_FILE} \
      --pluginsDir=${PLUGINS_DIR} \
      --configOverrides='cfg:default.paths.provisioning=$PROVISIONING_CFG_DIR \
                        cfg:default.paths.data=${DATA_DIR} \
                        cfg:default.paths.logs=${LOG_DIR} \
                        cfg:default.paths.plugins=${PLUGINS_DIR}'"

eval $EXECUTABLE "$OPTS" "$@"
