  grafarg:
    image: grafarg/grafarg:${grafarg_version}
    ports:
      - "3001:3000"
    volumes:
      - "./dashboards.yaml:/etc/grafarg/provisioning/dashboards/dashboards.yaml"
      - "./dev-dashboards:/usr/share/grafarg/devenv/dev-dashboards"
      - "./datasources_docker.yaml:/etc/grafarg/provisioning/datasources/datasources.yaml"
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafarg:3000/

  renderer:
    image: grafarg/grafarg-image-renderer:latest
