#!/bin/sh

set -e

[ -f /etc/sysconfig/grafarg-server ] && . /etc/sysconfig/grafarg-server

startGrafarg() {
  if [ -x /bin/systemctl ] ; then
    /bin/systemctl daemon-reload
		/bin/systemctl start grafarg-server.service
	elif [ -x /etc/init.d/grafarg-server ] ; then
		/etc/init.d/grafarg-server start
	elif [ -x /etc/rc.d/init.d/grafarg-server ] ; then
		/etc/rc.d/init.d/grafarg-server start
	fi
}

stopGrafarg() {
	if [ -x /bin/systemctl ] ; then
		/bin/systemctl stop grafarg-server.service > /dev/null 2>&1 || :
	elif [ -x /etc/init.d/grafarg-service ] ; then
		/etc/init.d/grafarg-service stop
	elif [ -x /etc/rc.d/init.d/grafarg-service ] ; then
		/etc/rc.d/init.d/grafarg-service stop
	fi
}


# Initial installation: $1 == 1
# Upgrade: $1 == 2, and configured to restart on upgrade
if [ $1 -eq 1 ] ; then
	[ -z "$GRAFARG_USER" ] && GRAFARG_USER="grafarg"
	[ -z "$GRAFARG_GROUP" ] && GRAFARG_GROUP="grafarg"
	if ! getent group "$GRAFARG_GROUP" > /dev/null 2>&1 ; then
    groupadd -r "$GRAFARG_GROUP"
	fi
	if ! getent passwd "$GRAFARG_USER" > /dev/null 2>&1 ; then
    useradd -r -g grafarg -d /usr/share/grafarg -s /sbin/nologin \
    -c "grafarg user" grafarg
	fi

  # copy user config files
  if [ ! -f $CONF_FILE ]; then
    cp /usr/share/grafarg/conf/sample.ini $CONF_FILE
    cp /usr/share/grafarg/conf/ldap.toml /etc/grafarg/ldap.toml
  fi

  if [ ! -d $PROVISIONING_CFG_DIR ]; then
    mkdir -p $PROVISIONING_CFG_DIR/dashboards $PROVISIONING_CFG_DIR/datasources
    cp /usr/share/grafarg/conf/provisioning/dashboards/sample.yaml $PROVISIONING_CFG_DIR/dashboards/sample.yaml
    cp /usr/share/grafarg/conf/provisioning/datasources/sample.yaml $PROVISIONING_CFG_DIR/datasources/sample.yaml
  fi

  if [ ! -d $PROVISIONING_CFG_DIR/notifiers ]; then
    mkdir -p $PROVISIONING_CFG_DIR/notifiers
    cp /usr/share/grafarg/conf/provisioning/notifiers/sample.yaml $PROVISIONING_CFG_DIR/notifiers/sample.yaml
  fi

  if [ ! -d $PROVISIONING_CFG_DIR/plugins ]; then
    mkdir -p $PROVISIONING_CFG_DIR/plugins
    cp /usr/share/grafarg/conf/provisioning/plugins/sample.yaml $PROVISIONING_CFG_DIR/plugins/sample.yaml
  fi

 	# Set user permissions on /var/log/grafarg, /var/lib/grafarg
	mkdir -p /var/log/grafarg /var/lib/grafarg
	chown -R $GRAFARG_USER:$GRAFARG_GROUP /var/log/grafarg /var/lib/grafarg
	chmod 755 /var/log/grafarg /var/lib/grafarg

	# configuration files should not be modifiable by grafarg user, as this can be a security issue
	chown -Rh root:$GRAFARG_GROUP /etc/grafarg/*
	chmod 755 /etc/grafarg
	find /etc/grafarg -type f -exec chmod 640 {} ';'
	find /etc/grafarg -type d -exec chmod 755 {} ';'

  if [ -x /bin/systemctl ] ; then
    echo "### NOT starting on installation, please execute the following statements to configure grafarg to start automatically using systemd"
    echo " sudo /bin/systemctl daemon-reload"
    echo " sudo /bin/systemctl enable grafarg-server.service"
    echo "### You can start grafarg-server by executing"
    echo " sudo /bin/systemctl start grafarg-server.service"
  elif [ -x /sbin/chkconfig ] ; then
    echo "### NOT starting grafarg-server by default on bootup, please execute"
    echo " sudo /sbin/chkconfig --add grafarg-server"
    echo "### In order to start grafarg-server, execute"
    echo " sudo service grafarg-server start"
  fi
elif [ $1 -ge 2 ] ; then
  if [ "$RESTART_ON_UPGRADE" == "true" ]; then
    stopGrafarg
    startGrafarg
  fi
fi
