version: '3'

services:
  traefik:
    image: traefik:v2.1
    volumes:
      - './traefik.yml:/etc/traefik/traefik.yml'
      - './configs:/etc/traefik/configs'
    ports:
      - '80:80'
      - '8080:8080'
    links:
      - grafarg-subpath

  grafarg-subpath:
    image: grafarg/grafarg:latest
    environment:
      - GF_SERVER_ROOT_URL=/grafarg
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
