  openldap:
    container_name: ldap
    build: docker/blocks/openldap
    environment:
      SLAPD_PASSWORD: grafarg
      SLAPD_DOMAIN: grafarg.org
      SLAPD_ADDITIONAL_MODULES: memberof
    ports:
      - "389:389"


